export default {interests: [ 
'Animals', 
'Pets', 
'Arts & Humanities', 
'Books & Literature', 
'Humanities', 
'Automotive', 
'Auto Parts', 
'Vehicle Brands', 
'Beauty & Personal Care', 
'Face & Body Care', 
'Fitness', 
'Hair Care & Products', 
'Spas & Beauty Services', 
'Business', 
'Advertising & Marketing', 
'Business Services & Consulting', 
'Corporate Events', 
'E-Commerce', 
'Human Resources', 
'Management & Corporate Operations', 
'Office & Printing Services', 
'Small Business', 
'Computers & Electronics', 
'Computer Security', 
'Consumer Electronics', 
'Audio Equipment', 
'Home Video', 
'Personal Electronics', 
'Electronics & Electrical', 
'Enterprise Technology', 
'Hardware', 
'Hardware Components', 
'Peripherals', 
'Storage', 
'Networking', 
'Programming', 
'Software', 
'Graphics & Publishing', 
'Internet Software', 
'Operating Systems', 
'Entertainment', 
'Comics & Animation', 
'Movies', 
'Multimedia Content', 
'Music', 
'TV', 
'TV Programs', 
'Finance & Insurance', 
'Credit & Lending', 
'Insurance', 
'Food & Drink', 
'Restaurants', 
'Games', 
'Video Games', 
'Home & Garden', 
'Home Furnishings', 
'Industries', 
'Aerospace & Defense', 
'Agriculture & Forestry', 
'Chemicals', 
'Construction & Maintenance', 
'Building Materials', 
'Wood & Plastics', 
'Design', 
'Energy & Utilities', 
'Industrial Materials & Equipment', 
'Manufacturing', 
'Retail Trade', 
'Transportation & Logistics', 
'Internet', 
'Online Goodies', 
'Web Services', 
'Lifestyles', 
'Activism & Social Issues', 
'Parenting & Family', 
'Local', 
'Regional Content', 
'Central & Eastern Europe', 
'Central & South Asia', 
'East Asia', 
'Mexico & Central America', 
'Middle East', 
'Oceania', 
'South America', 
'Southeast Asia', 
'US & Canada', 
'Western Europe', 
'News & Current Events', 
'Politics', 
'Photo & Video', 
'Photo & Video Equipment', 
'Cameras & Camcorders', 
'Real Estate', 
'Recreation', 
'Hobbies', 
'Outdoors', 
'Reference', 
'Science', 
'Biological Sciences', 
'Shopping', 
'Apparel', 
'Consumer Affairs & Product Reviews', 
'Customer Services', 
'Flowers Gifts & Greetings', 
'Luxury Goods', 
'Social Networks & Online Communities', 
'Dating & Relationships', 
'Society', 
'Education', 
'Government & Regulatory Bodies', 
'Legal', 
'Military', 
'Public Safety', 
'Social Science', 
'Social Services', 
'Sports', 
'Combat Sports', 
'Telecommunications', 
'Mobile & Wireless', 
'Service Providers', 
'Phone Service Providers', 
'Travel', 
'Vacation Destinations']
}