export default {occupations: ["Account Coordinator", 
"Account Executive", 
"Account Representative",
"Accounting Assistant", 
"Actuary", 
"Administrative Assistant", 
"Administrative Officer", 
"Analog Circuit Design manager", 
"Analyst Programmer", 
"Assistant Manager", 
"Assistant Media Planner", 
"Assistant Professor", 
"Associate Professor", 
"Automation Specialist", 
"Biostatistician", 
"Budget/Accounting Analyst", 
"Business Systems Development Analyst", 
"Chemical Engineer", 
"Chief Design Engineer", 
"Clinical Specialist", 
"Community Outreach Specialist",
"Compensation Analyst",  
"Computer Systems Analyst", 
"Cost Accountant", 
"Data Coordiator", 
"Database Administrator", 
"Dental Hygienist", 
"Design Engineer", 
"Desktop Support Technician", 
"Director of Sales", 
"Editor", 
"Electrical Engineer", 
"Environmental Specialist", 
"Environmental Tech", 
"Executive Secretary", 
"Financial Advisor", 
"Food Chemist", 
"General Manager", 
"Geological Engineer",
"Geologist", 
"GIS Technical Architect", 
"Graphic Designer", 
"Health Coach", 
"Help Desk Technician", 
"Human Resources Assistant", 
"Human Resources Manager", 
"Information Systems Manager", 
"Internal Auditor", 
"Librarian", 
"Librarian", 
"Marketing Assistant", 
"Marketing Manager", 
"Mechanical Systems Engineer", 
"Nuclear Power Engineer", 
"Nurse Practicioner", 
"Nurse", 
"Occupational Therapist", 
"Office Assistant", 
"Operator", 
"Paralegal", 
"Payment Adjustment Coordinator", 
"Pharmacist",  
"Physical Therapy Assistant", 
"Product Engineer", 
"Professor", 
"Programmer Analyst", 
"Programmer", 
"Project Manager", 
"Quality Control Specialist", 
"Quality Engineer", 
"Recruiter",
"Registered Nurse", 
"Research Assistant", 
"Research Associate", 
"Research Nurse", 
"Safety Technician", 
"Sales Associate", 
"Sales Representative", 
"Senior Developer", 
"Senior Editor", 
"Senior Financial Analyst", 
"Senior Sales Associate", 
"Software Consultant", 
"Software Test Engineer", 
"Speech Pathologist", 
"Staff Accountant", 
"Staff Scientist",
"Statistician", 
"Structural Analysis Engineer", 
"Systems Administrator", 
"Tax Accountant", 
"Teacher", 
"Technical Writer", 
"VP Accounting", 
"VP Marketing", 
"VP Product Management", 
"VP Quality Control", 
"VP Sales", 
"Web Designer", 
"Web Developer"]}